sonar.projectKey=iris-mlops-devsecops-api
sonar.organization=hrithikgopakumar

sonar.sources=.
sonar.inclusions=app.py,train.py
sonar.exclusions=VM1/**,iris_model/**,mlruns/**,**/__pycache__/**

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8